### ISSUE TITLE
Show where the broken link is found with silent

### ISSUE THREAD

**Issue by XhmikosR** [JustinBeckwith/linkinator#81]
Currently, when silent is used, only the broken link is printed:

```
  [404] https://foo.bar/docs/index.html
  [404] https:///en/404.md/
```

I think it's be very useful if the link that the broken one is on was printed too.

/CC @Johann-S

**Comment by JustinBeckwith** [comment]
Pretty sure I fixed this in #35.  The failed links are printed as they're experienced, but the final link report groups results by parent page.  Please take a look at the latest version and let me know what you think!

**Comment by XhmikosR** [comment]
@JustinBeckwith it seems now even with `silent` the scanned URL is shown :/

**Comment by XhmikosR** [comment]
See https://github.com/twbs/bootstrap/pull/29663/checks?check_run_id=298839115#step:8:225

**Comment by XhmikosR** [comment]
Also, I still don't see the failed page :/

https://github.com/twbs/bootstrap/runs/298866365#step:9:7

**Comment by JustinBeckwith** [comment]
So - the fix for the url title heading is here:
https://github.com/JustinBeckwith/linkinator/pull/102

Taking a closer look at the output - I think it's actually working, the content is just hidden in a sea of passing link references :) It should print a top level link to the page being scanned, then links under that with the status code.  Take a look at the latest version!

**Comment by XhmikosR** [comment]
@JustinBeckwith thanks for the quick fix :)

Here's the output https://github.com/twbs/bootstrap/runs/300584669#step:9:8

So basically now you output the failed links as we scan, but also at the end, is that correct? It seems a little redundant to output them twice and a little confusing IMO.

**Comment by JustinBeckwith** [comment]
Glad to hear the fix worked out.  On showing the data twice ... I could really use some ideas here.  With the move to concurrent scanning, it means that results come and go out of any reasonable order.  So the only way to show an aggregated view (like at the end) is to buffer all the results, and spit them out at the end.  The problem with that approach is that you don't see anything during the scan - it just sits there quietly.  I can see two ways this thing is used:
1. Interactive - for folks that want to just `npx linkinator` from the cmdline, I would want to see the results as they come.  The summary at the end is great too.
2. In CI - now here's where I agree - having the output show up twice is a little weird.  

You have any ideas on how we could show reasonable progress during the scan, and the summary with the rollup data?

**Comment by JustinBeckwith** [comment]
Also - since the original issue is resolved (we show the parent now in silent mode), I'm going to close this.  I started a separate discussion for the double output problem in #115.
